#!/usr/bin/perl

my $a1 = "This is local variable";                               # with keyword ' my ' will set variable to use within file
$a = "This is global variable";
$b = "This is global variable";                                 # without keyword ' my ' will set variable to use both within and outside of file.
our $c = "This is global variable (after explicit import)";     # with keyword ' our ' will set variable to use globally by explicitly importing that variable
print "This is perl_prac2 file.\n";

=note
$a and $b are bydefault global variables